name: Test Getting Git Branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  get_git_branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${GITHUB_BRANCH##*/}"
        env:
          GITHUB_BRANCH: ${{ github.ref }}
