name: Test Getting Git Branch 1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  get_git_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get source branch name
        shell: bash
        run: echo "Source branch: ${GITHUB_BRANCH##*/}"
        env:
          GITHUB_BRANCH: ${{ github.ref }}

      - name: If main # 1. check compare branch is dev, 2. set MAX_EXAMPLES to 50
        if: ${{ GITHUB_BRANCH == 'main' }}
        shell: bash
        run: echo "ME=50"
        env:
          ME: 5

      - name: Create env file
        run: |
          touch .env
          echo WEB3_INFURA_PROJECT_ID=${{ secrets.WEB3_INFURA_PROJECT_ID }} >> .env
          echo ETHERSCAN_TOKEN=${{ secrets.ETHERSCAN_TOKEN }} >> .env
          echo MAX_EXAMPLES=${{ ME }} >> .env
          cat .env

      - name: Cache Compiler Installations
        uses: actions/cache@v2
        with:
          path: |
            ~/.solcx
            ~/.vvm
          key: compiler-cache

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Install Ganache
        run: npm install -g ganache-cli@6.12.1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Compile Code
        run: brownie compile --size

      - name: Run Tests
        run: brownie test -vv -s --gas
